# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy new debug build to AppCenter"
  lane :deployAppCenterDebug do

    gradle(task: "clean assembleDebug")

    appcenter_upload(
      api_token: ENV["APP_CENTER_TOKEN"],
      owner_name: "Patronage-2021",
      app_name: "Patronage2021",
      destinations: "Collaborators, Testers QA",
      file: "./app/build/outputs/apk/debug/app-debug.apk",
      notify_testers: false
    )
  end
  
  desc "Deploy a beta version to Google Play"
  lane :beta do
    
	# Clean build folder
    gradle(
      task: "clean"
    )
	
	vc = google_play_track_version_codes
    vcb = google_play_track_version_codes(track: 'beta')
    max_value = [vc[0].to_i, vcb[0].to_i].max
    version_updated = max_value + 1
    increment_version_code(gradle_file_path: "./app/build.gradle", version_code: version_updated.to_i)
	increment_version_code(gradle_file_path: "./shared.gradle", version_code: version_updated.to_i)

    # Do the bundle of the application
    gradle(
      task: 'bundle',
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file" => Dir.pwd + "/upload-keystore.jks",
    "android.injected.signing.store.password" => "Patronageage2021",
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => "Patronageage2021"
      }
    )
    upload_to_play_store(track: 'beta')
  end
  
  
end
