name: Beta Release

on:
  push:
    branches:
      - feature/IP2-573
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
            - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      - run: bundle install
      - run: fastlane env
      - run: fastlane install_plugins --verbose
            - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'beta'